name: Github CI Audit check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verify Dependencies
        run: |
          go mod verify
          go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install static check
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run static check
        run: staticcheck ./...

      - name: Run Tests
        run: go test -race ./...
